{% set name = "rip2" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MilesCranmer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 657ded2ee364e0d548697c0de28ae4e8d9564c0b5c63fd16b6718edba9a33554

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rip --version

about:
  home: https://github.com/MilesCranmer/rip2
  dev_url: https://github.com/MilesCranmer/rip2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A safe and ergonomic alternative to rm

extra:
  recipe-maintainers:
    - apcamargo
