{% set name = "rip2" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MilesCranmer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e6d3143958b838ebbf421fb933d8e46ecc28c8298f435bdf09f647b4def452f6

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - rip --version

about:
  home: https://github.com/MilesCranmer/rip2
  dev_url: https://github.com/MilesCranmer/rip2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A safe and ergonomic alternative to rm

extra:
  recipe-maintainers:
    - apcamargo
